# A github workflow to build a Raspberry Pi Pico binary
# and upload it to the github release page.
#
# This workflow will build a binary using Cmake for the Raspberry Pi Pico
# and upload it to the github release page.
name: Build
on: [push]
jobs:
  build:
    permissions: write-all
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Install dependencies
        run: sudo apt update && sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libstdc++-arm-none-eabi-newlib

      - name: Checkout
        uses: actions/checkout@v2

      # Get Raspberry Pi Pico SDK
      - name: Clone Raspberry Pi Pico SDK
        run: git clone --recurse-submodules https://github.com/raspberrypi/pico-sdk ${{github.workspace}}/pico-sdk

      - name: Configure CMake
        run: export PICO_SDK_PATH="${{github.workspace}}/pico-sdk"; cmake -B ${{github.workspace}}/build -S .

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build

        # Upload
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{github.workspace}}/build/SimplePicoMidiController.uf2
          asset_name: SimplePicoMidiController.uf
          prerelease: true
          # body: ${{ steps.release.outputs.RELEASE_BODY }}
          tag: ${{ github.ref }}
